config/routes.rb
RailsinstallerDemo::Application.routes.draw do
	#Reformed url scheme
	root :to => 'welcome#index'
	
	match 'user/:username/activity' => 'users#activity'

	match 'login' => 'user_sessions#new', :via => :get
	match 'login', :to => 'user_sessions#create', :via => :post
	match 'logout' => 'user_sessions#destroy', :as => :logout
	#resources :sessions, only: [:new, :create, :destroy]
	#resources :user_sessions
	
	match 'about' => 'welcome#about'
	match 'help' => 'welcome#help'
	match 'api/docs' => 'welcome#api_docs'
	match 'legal' => 'welcome#legal'

	match 'signup' => 'users#new', :via => :get
	match 'signup' => 'users#create', :via => :post
	
	match 'user/:id' => 'users#show', :as => :user
	
	match 'mark_read' => 'users#mark_read'
  match 'dismiss' => 'users#dismiss_notification', :as => :dismiss

	match 'dynamic_score' => 'users#dynamic_score'
	match ':username/notifications' => 'users#notifications'
	match 'public_events/:id' => 'users#public_events'
	match 'dynamic_search' => 'users#dynamic_search'

	match 'home' => 'users#home'
	
	match 'profile' => 'connections#index', :as => :connections, :via=>:get
	match 'profile' => 'connections#create', :as => :connections_create, :via=>:post
	match 'profile' => 'users#update_description', :as => :update_description, :via=>:put

	match 'profile/new' => 'connections#new', :as => :connections_new
	
	match 'profile/connect' => 'users#associate', :via => :get
	match 'profile/connect' => 'users#request_association', :via => :post
	match 'profile/connect/:id' => 'users#answer_association', :via => :get
	match 'profile/connect/:id/confirm' => 'users#confirm_association', :via => :get
	match 'profile/connect/:id/reject' => 'users#reject_association', :via => :get

	
	match 'activate/:code' => 'users#activate', :as => :activate, :via => :get
	match 'activate/:code' => 'users#finalize_activation', :as => :activate, :via => :put


	match 'invite' => 'rating_invitations#new', :via => :get
	match 'invite/new' => 'rating_invitations#create', :via => :post
	match 'invitation/:id' => 'rating_invitations#show'
	match 'invitation/:id/regenerate' => 'rating_invitations#regenerate', :as => :regenerate_invitation
	match 'invitation/:id/delete' => 'rating_invitations#delete', :as => :delete_invitation

	match '/i/:id' => 'rating_invitations#show_unique', :as => :i
	match '/accept/:id' => 'ratings#accept_invitation', :as => :accept
	match 'invite/email' => 'rating_invitations#email_invite', :via => :get
	match 'invite/email' => 'rating_invitations#send_email_invite', :via => :post

 
	
	match 'rate' => 'users#confirm_ratings'
	match 'rate/:id' => 'ratings#rate', :via => :get, :as => :rating
	match 'rate/:id' => 'ratings#update', :via => :put
	
	match 'share' => 'links#index', :via => :get
	match 'share' => 'links#create', :via => :post
	match 's/:id' => 'links#show'
	match 's/:id/delete' => 'links#destroy'
	
	match 'settings' => 'users#show_settings', :via => :get
	match 'settings' => 'users#update', :via => :put, :as => :update_settings
	match 'settings/v' => 'users#verification_email'
	match 'v/:code' => 'users#verify'
	
	match 'api/secure' => 'api#api_secure', :as => :api_secure, :via => :POST
	match 'api/score' => 'api#api_score', :as => :api_score, :via => :GET
	match 'api/signup' => 'api#api_signup', :as => :api_signup, :via => :POST
	match 'api/invitation' => 'api#api_invitation', :as => :api_invitation, :via => :GET
	match 'api/invite' => 'api#api_invite', :as => :api_invite, :via => :POST
	match 'api/rate' => 'api#api_rate', :as => :api_rate, :via => :POST
	match 'api/set_public_key' => 'api#api_set_public_key', :as => :api_set_public_key, :via => :POST
	match 'api/next_sequence' => 'api#api_next_sequence', :as => :api_next_sequence, :via => :GET
end

app/models/connection.rb
require 'securerandom'

class Connection < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :website_name
	validates_presence_of :homepage_url
	#validate :website_url_is_valid
	validate :homepage_url_is_valid

	#def website_url_is_valid
	#	if website_url.include? " "
	#		errors.add(:website_url, "includes invalid characters")
	#	end
	#end

	def homepage_url_is_valid
		if homepage_url.include? " "
			errors.add(:homepage_url, "includes invalid characters")
		end
	end

	def self.create_hash
		SecureRandom::base64(12).gsub('+','-').gsub('/','_')
	end
	
	def short_description
		if website_name.length > 22
			website_name[0..19] + "..."
		else
			website_name
		end
	end

	def show_homepage_url
		sanitize_link homepage_url
	end

	def show_website_url
		sanitize_link website_url
	end

	#private #What is this doing here?

	def sanitize_link(url)
		prefix = "http://"
		url = prefix + url unless url.include? prefix unless url == ""
		return url
	end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
	before_filter :login_required, :only => [:index, :new, :edit]
	include ApplicationHelper

	def index
		bubbles
		@connections = Connection.where("user_id = ?", current_user.id).reverse
		@facets = current_user.facets
		respond_to do |format|
		  format.html # index.html.erb
		  format.json { render json: @connections }
		end
	end

	def show
		@connection = Connection.find_by_unique_token(params[:token])
		if !@connection.nil?
			if @connection.user.username != params[:username].downcase
				@connection = nil
			end
		end

		respond_to do |format|
			format.html
			format.json { render json: @connection }
		end
	end

	def new
		bubbles
		@connection = Connection.new

		respond_to do |format|
		  format.html # new.html.erb
		  format.json { render json: @connection }
		end
	end

	def edit
		@connection = Connection.find_by_unique_token(params[:token])
		if @connection.user != current_user
			redirect_to("/")
		else
			if !@connection.nil?
				#target_url = '/connections/'+@connection.user.pretty_name+'/'+@connection.unique_token+'/update/'
				if @connection.user.username != params[:username].downcase
					@connection = nil
				end
			end
			respond_to do |format|
				format.html # edit.html.erb
				format.json { render json: @connection }
			end
		end
	end

	def create
		@connection = Connection.new(params[:connection])
		@connection.user = current_user
		@connection.unique_token = Connection.create_hash
		respond_to do |format|
			if @connection.save
				target_url = '/profile'# '/connections/'+@connection.user.pretty_name+'/'+@connection.unique_token
				format.html { redirect_to target_url, notice: 'Connection was successfully created.' }
				format.json { render json: target_url, status: :created, location: @connection }
			else
				format.html { render action: "new" }
				format.json { render json: @connection.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		@connection = Connection.find_by_unique_token(params[:token])
		if !@connection.nil?
			if @connection.user.username != params[:username].downcase
				@connection = nil
			end
		end
		respond_to do |format|
			if @connection.update_attributes(params[:connection])
				format.html { redirect_to '/connections/', notice: 'Connection was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @connection.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@connection = Connection.find(params[:id])
		if @connection.user != current_user
			redirect_to "/"
		else
			@connection.destroy
			respond_to do |format|
				format.html { redirect_to connections_url }
				format.json { head :no_content }
			end
		end
	end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<div class="row">
  <div class="span4 offset4">
    <%= form_for(@connection, :url=>target) do |f| %>
  <% if @connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% @connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_of_the_other_website %>
    <%= f.text_field :website_name %>
  </div>
  <div class="field">
    URL of the website <small>(for example: <tt>www.example.com</tt>)</small>
    <%= f.text_field :website_url %>
  </div>
  <div class="field">
    <%= f.label 'Your username on the website' %>
    <%= f.text_field :account_name %>
  </div>
  <div class="field">
    Link to your user page on the website <small>(for example: <tt>www.example.com/user/MyName</tt>)</small> (optional)
    <%= f.text_field :homepage_url %>
  </div>

  
  
  <div class="actions">
    <%= f.submit class: "btn btn-large btn-primary" %>
  </div>
<% end %>

  </div>
</div>

app/views/connections/edit.html.erb
<% if notice %>
	<p id="notice">
	<%= notice %>
	</p>
<% end %>

<div>
	<h3 style="display:inline">
		<% if current_user and current_user.id == @connection.user_id %>
			<a href="/user/<%= current_user.pretty_name %>" class="userlink">Welcome, <%= current_user.pretty_name %>!</a>
			&raquo; <a href="/connections/" class="userlink">manage connections</a>
		<% else %>
			<a href="/users/<%= @connection.user.pretty_name %>" class="userlink"><%= @connection.user.pretty_name %>'s profile</a>
			&raquo; connection
		<% end %>
		&raquo; <%= @connection.short_description %></h3> <i class="icon-edit"></i>
	</h3>
</div>

<%= render 'form', :target => '/connections/'+@connection.user.pretty_name+'/'+@connection.unique_token+'/update/' %>

app/views/connections/index.html.erb
<style>
	.connection {
		margin-right:15px;
	}
	.marked {
		text-decoration: line-through;
		color: #800;
	}
	a.marked:hover, a.marked:active {
		color:#f00;
	}
	.unbreakableForm {
		white-space: nowrap;
	}

</style>


<% unless notice.nil? %>
<div id="notice" onclick="$(this).css('display','none')">
	<%= notice %>
</div>
<% end %>

<% unless current_user %>

	You are not logged in.

<% else %>

	<h2 class="subheader">public profile text</h2>

	<%= form_for(current_user, :url=>"/profile") do |f| %>
		<%= f.text_area :description, :maxlength => 360 %>
		<%= f.submit "update", class: "button", style: "font-size:20px;" %><div class="right">remaining: <span id="remaining"><%= 360-(current_user.description.nil? ? 0 : current_user.description.length) %></span></div>
	<% end %>

	<hr/>

	<h2 class="subheader">identities</h2>

	<p>Tip: Use <a href="/about#3.5">verifiable links</a> if possible.<i class="icon-large icon-red icon-remove" style="position:absolute; left:-999999999px;"></i></p>

	<p style="font-size:16pt;">
	<% if @connections.length > 0 %>
		<span id="connections">
		<% @connections.each do |connection| %>
		<span class="connection">
		<a href="#" onclick="$(this).children('i').toggleClass('icon-black').toggleClass('icon-red'); $(this).next().toggleClass('marked'); return false;"><i class="icon-large icon-black icon-remove"></i></a>
		<a target="_blank" href="<%= connection.show_homepage_url %>" onclick=""><%= connection.website_name %></a></span>
		<% end %></span>
	<% end %>


	<span class="unbreakableForm">
		<input style="width:144px; display:inline;" type="text" placeholder="new link text" />
		<input style="width:360px; display:inline;" type="text" placeholder="http://www.example.com/myname" />
	</span>
	<%= link_to 'add/remove', connections_new_path, class: 'button' %>
	</p>


		

<% end %>
<script>
	$('textarea').keypress(function(){
		var thing = this;
		setTimeout(function(){$("#remaining").html(360 - thing.value.length);}, 10);
    });
</script>

app/views/connections/new.html.erb
  <!-- profile/new -->
  <div class='center panel large'>		
  	<h3 class='subheader'>Connect Profiles From Other Sites</h3>
  </div>
  <div class='columns-12 large'>	  	
  	<%= form_for(@connection, :url=>"/profile") do |f| %>

  	<label>Website Name</label>
  	<%= f.text_field :website_name %>

  	<% if @connection.errors[:website_name].length >0 %>
  	<%= @connection.errors[:website_name].join(', ') %>
  	<% end %>


  	URL of your page there
  	<%= f.text_field :homepage_url %>

  	<% if @connection.errors[:homepage_url].length >0 %>
  	<%= @connection.errors[:homepage_url].join(', ') %>
  	<% end %>


  	<br>

  	<%= f.submit "add to profile", class: "button right" %>
  	<% end %>
  </div>
</div>

app/views/connections/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<% if @connection.nil? %>
	<h3>Connection: not found</h3>
	<h4 class="link_expired">The link is expired or invalid.</h4>
<% else %>
	<div>
		<h3>
			<% if current_user and current_user.id == @connection.user_id %>
				<%= link_to "Welcome, #{current_user.pretty_name}!", "/user/#{current_user.pretty_name}", :class => "userlink" %>
				&raquo; 
				<%= link_to "manage connections", "/connections/", :class => "userlink" %>
			<% else %>
				<%= link_to "#{@connection.user.pretty_name}'s profile", "/user/#{@connection.user.pretty_name}", :class => "userlink" %>
				&raquo; connection
			<% end %>
			&raquo; <%= @connection.short_description %>
		</h3>
	</div>

	<div class="span6 offset3">
		<div class="rounded_box">
			<p>
			Endorster user
				<a href="/user/<%= @connection.user.pretty_name %>"> <i class="icon-user"></i> <%= @connection.user.pretty_name %></a>
			</p>
			<p>
			is user
			<% if @connection.homepage_url.length > 0 %>
				<a target="_blank" href="<%= @connection.show_homepage_url %>"><%= @connection.account_name %> <i class="icon-share"></i></a>
			<% else %>
				<b><%= @connection.account_name %></b>
			<% end %>
			</p>
			<p>
			asdf
			</p>
		</div>
	</div>
<% end %>

app/views/connections/~_form.html.erb
<%= form_for(@connection, :url=>target) do |f| %>
  <% if @connection.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

    <ul>
      <% @connection.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name_of_the_other_website %>
    <%= f.text_field :website_name %>
  </div>
  <div class="field">
    URL of the website <small>(for example: <tt>www.example.com</tt>)</small>
    <%= f.text_field :website_url %>
  </div>
  <div class="field">
    <%= f.label 'Your username on the website' %>
    <%= f.text_field :account_name %>
  </div>
  <div class="field">
    Link to your user page on the website <small>(for example: <tt>www.example.com/user/MyName</tt>)</small> (optional)
    <%= f.text_field :homepage_url %>
  </div>
  <div class="field">
    Allow this website to make ratings on behalf of your Endorster account?
    <%= f.check_box :write_permission %>
  </div>
  <div class="field">
    Show this account connection on your public profile?
    <%= f.check_box :public %>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
  <% end %>

app/views/connections/~edit.html.erb
<% if notice %>
	<p id="notice">
	<%= notice %>
	</p>
<% end %>

<div>
	<h3 style="display:inline">
		<% if current_user and current_user.id == @connection.user_id %>
			<a href="/user/<%= current_user.pretty_name %>" class="userlink">Welcome, <%= current_user.pretty_name %>!</a>
			&raquo; <a href="/connections/" class="userlink">manage connections</a>
		<% else %>
			<a href="/users/<%= @connection.user.pretty_name %>" class="userlink"><%= @connection.user.pretty_name %>'s profile</a>
			&raquo; connection
		<% end %>
		&raquo; <%= @connection.short_description %></h3> <i class="icon-edit"></i>
	</h3>
</div>

<%= render 'form', :target => '/connections/'+@connection.user.pretty_name+'/'+@connection.unique_token+'/update/' %>