config/routes.rb
RailsinstallerDemo::Application.routes.draw do
	#Reformed url scheme
	root :to => 'welcome#index'
	
	match 'user/:username/activity' => 'users#activity'

	match 'login' => 'user_sessions#new', :via => :get
	match 'login', :to => 'user_sessions#create', :via => :post
	match 'logout' => 'user_sessions#destroy', :as => :logout
	#resources :sessions, only: [:new, :create, :destroy]
	#resources :user_sessions
	
	match 'about' => 'welcome#about'
	match 'help' => 'welcome#help'
	match 'api/docs' => 'welcome#api_docs'
	match 'legal' => 'welcome#legal'

	match 'signup' => 'users#new', :via => :get
	match 'signup' => 'users#create', :via => :post
	
	match 'user/:id' => 'users#show', :as => :user
	
	match 'mark_read' => 'users#mark_read'
  match 'dismiss' => 'users#dismiss_notification', :as => :dismiss

	match 'dynamic_score' => 'users#dynamic_score'
	match ':username/notifications' => 'users#notifications'
	match 'public_events/:id' => 'users#public_events'
	match 'dynamic_search' => 'users#dynamic_search'

	match 'home' => 'users#home'
	
	match 'profile' => 'connections#index', :as => :connections, :via=>:get
	match 'profile' => 'connections#create', :as => :connections_create, :via=>:post
	match 'profile' => 'users#update_description', :as => :update_description, :via=>:put

	match 'profile/new' => 'connections#new', :as => :connections_new
	
	match 'profile/connect' => 'users#associate', :via => :get
	match 'profile/connect' => 'users#request_association', :via => :post
	match 'profile/connect/:id' => 'users#answer_association', :via => :get
	match 'profile/connect/:id/confirm' => 'users#confirm_association', :via => :get
	match 'profile/connect/:id/reject' => 'users#reject_association', :via => :get

	
	match 'activate/:code' => 'users#activate', :as => :activate, :via => :get
	match 'activate/:code' => 'users#finalize_activation', :as => :activate, :via => :put


	match 'invite' => 'rating_invitations#new', :via => :get
	match 'invite/new' => 'rating_invitations#create', :via => :post
	match 'invitation/:id' => 'rating_invitations#show'
	match 'invitation/:id/regenerate' => 'rating_invitations#regenerate', :as => :regenerate_invitation
	match 'invitation/:id/delete' => 'rating_invitations#delete', :as => :delete_invitation

	match '/i/:id' => 'rating_invitations#show_unique', :as => :i
	match '/accept/:id' => 'ratings#accept_invitation', :as => :accept
	match 'invite/email' => 'rating_invitations#email_invite', :via => :get
	match 'invite/email' => 'rating_invitations#send_email_invite', :via => :post

 
	
	match 'rate' => 'users#confirm_ratings'
	match 'rate/:id' => 'ratings#rate', :via => :get, :as => :rating
	match 'rate/:id' => 'ratings#update', :via => :put
	
	match 'share' => 'links#index', :via => :get
	match 'share' => 'links#create', :via => :post
	match 's/:id' => 'links#show'
	match 's/:id/delete' => 'links#destroy'
	
	match 'settings' => 'users#show_settings', :via => :get
	match 'settings' => 'users#update', :via => :put, :as => :update_settings
	match 'settings/v' => 'users#verification_email'
	match 'v/:code' => 'users#verify'
	
	match 'api/secure' => 'api#api_secure', :as => :api_secure, :via => :POST
	match 'api/score' => 'api#api_score', :as => :api_score, :via => :GET
	match 'api/signup' => 'api#api_signup', :as => :api_signup, :via => :POST
	match 'api/invitation' => 'api#api_invitation', :as => :api_invitation, :via => :GET
	match 'api/invite' => 'api#api_invite', :as => :api_invite, :via => :POST
	match 'api/rate' => 'api#api_rate', :as => :api_rate, :via => :POST
	match 'api/set_public_key' => 'api#api_set_public_key', :as => :api_set_public_key, :via => :POST
	match 'api/next_sequence' => 'api#api_next_sequence', :as => :api_next_sequence, :via => :GET
end

app/controllers/users_controller.rb
require 'depth_first_search'
require 'digest'
require 'application_helper'
include ApplicationHelper

class UsersController < ApplicationController
	before_filter :login_required, :only => [:show_settings, :confirm_ratings, :associate, :request_association]
	before_filter :bubbles
	def index
		@users = User.all
		
		respond_to do |format|
			format.html # index.html.erb
			#format.json { render json: @users } #must be disabled for security reasons
		end
	end
	
	def associate
		@association_request = AssociationRequest.new
		respond_to do |format|
			format.html # associate.html.erb
		end
	end
	

		# format.html { redirect_to '/profile', notice: 'updated profile text' }
		# 	else
		# 		format.html { render action: "connections#index" }

		def request_association
			request = {
				:from => current_user,
				:to => User.find_by_username(params[:association_request][:to].downcase),
				:is_from_master_to_facet => false 
			}
			@association_request = AssociationRequest.new(request)
			if request[:to].nil?
				@notice = 'The name entered is not a valid Endorster username.'
			elsif !request[:is_from_master_to_facet] and !current_user.master.nil?
			#Your account is already owned by user x, so it can't be owned by a different user as well.
			@notice = "Your account is already owned by user "+current_user.master.pretty_name+", so it can't be owned by a different user as well."
		end
		respond_to do |format|
			if @association_request.errors.empty? and @association_request.save
				Notification.generate_notification(:identity_claim, @association_request).save
				@notice = 'Your connection request has been sent. Log in as '+request[:to].pretty_name+' to accept it.'
				format.html { redirect_to '/settings', notice: @notice }
			else
				#format.json { render json: @user.errors, status: :unprocessable_entity }
				format.html { redirect_to '/settings', notice: @notice  }
			end
		end
	end
	

	def answer_association
		@association_request = AssociationRequest.find_by_id(params[:id])
		if @association_request.nil? or @association_request.to != current_user
			respond_to do |format|
				format.html { redirect_to '/' }
			end
		else
			respond_to do |format|
				format.html
			end
		end
	end

	def reject_association
		ar = AssociationRequest.find_by_id(params[:id])
		if ar.to != current_user
			respond_to do |format|
				format.html { redirect_to '/' }
			end
		else
			ar.delete
			dismiss_notifications
			respond_to do |format|
				format.html { redirect_to '/profile', notice: 'The connection has been rejected.' }
			end
		end
	end

	def confirm_association #Merge the two accounts. Cannot be undone! (Or shouldn't, at least.)
		ar = AssociationRequest.find_by_id(params[:id])
		if ar.to != current_user
			respond_to do |format|
				format.html { redirect_to '/' }
			end
		else
			ar.from.master = current_user
			ar.from.facets.each do |facet|
				facet.master = current_user
				facet.save
			end
			ar.from.save
			
			#If there are any ratings which are revealed to be self-ratings, then mark them as such.
			person_ids = [current_user.id]
			current_user.facets.each do |facet|
				person_ids << facet.id
			end
			person_ids_string = person_ids.join(",")
			self_ratings = Rating.where("rater_id IN (#{person_ids_string}) AND ratee_id IN (#{person_ids_string})")
			#self_ratings.each do |sr|
			#	sr.is_self_rating = true #needs to be implemented
			#	sr.save
			#end
			
			dismiss_notifications
			respond_to do |format|
				format.html { redirect_to '/profile', notice: 'The connection has been confirmed.' }
			end
		end
	end

	def dynamic_score
		user = User.find_by_username(params[:username])
		if user
			@score = DepthFirstSearch.score(current_user, user) unless current_user == @user || current_user.nil?
			@backscore = DepthFirstSearch.score(user, current_user) unless current_user == @user || current_user.nil?
			bs_color = color_for_score(@backscore)
			s_color = color_for_score(@score)
		else
			@error = "Couldn't find that user"
		end
		respond_to do |format|
			msg = { score: @score, backscore: @backscore, backscore_color: bs_color, score_color: s_color, error: @error }
			format.json  { render :json => msg } 
		end
	end

	def dynamic_search
		term = params[:term]
		users = User.all
		values = []
		users.each do |u|
			values << u.username if u.username.include?(term)
		end
		puts values


		respond_to do |format|
			format.json  { render :json => values }
		end
	end

	def show
		@page = 'overview'
		@viewing_user = User.find_by_username(params[:id].downcase)
		@facets = @viewing_user.facets
		@score = DepthFirstSearch.score(current_user, @viewing_user) unless current_user == @viewing_user || current_user.nil?
		@backscore = DepthFirstSearch.score(@viewing_user, current_user) unless current_user == @viewing_user || current_user.nil?
		if @viewing_user == current_user
			@association_requests = AssociationRequest.where("to_id =?", current_user)
		else
			@association_requests = []
		end
		@connections = Connection.where("user_id = ?", @viewing_user).reverse
		respond_to do |format|
			if @viewing_user
				@iratings = Rating.where("ratee_id = ?", @viewing_user.id).where("dateclosed IS NOT NULL")
				@oratings = Rating.where("rater_id = ?", @viewing_user.id).where("dateclosed IS NOT NULL")
	        format.html # show.html.erb
	      else
	      	format.html { redirect_to users_url, :notice => "User doesn't exist" }
	      end
	    end
	  end

	  def notifications
	  	@user = User.find_by_username(params[:username])
	  	@notifications = @user.notifications
	  end

	  def activity
	  	@page = 'activity'
	  	@viewing_user = User.find_by_username(params[:username].downcase)
	  	@ratings =  @viewing_user.outgoingratings + @viewing_user.incomingratings 
	  	@ratings.sort { |x,y| y.created_at <=> x.created_at}
	  end

	  def dismiss_notification
	  	if current_user
	  		@current_user.notifications.each do |notification|
	  			notification.destroy
	  		end
	  	else
			# do nothing.
		end
	end

	def mark_read
		notification = Notification.find(params[:id])
		notification.read = true
		notification.save
		if notification.base_url == "/invitation/"
			render :js => "window.location = #{notification.base_url+notification.thing_id}"
		else
			render :js => "window.location = #{notification.base_url}"
		end
	end
	
	def home
		respond_to do |format|
			if current_user
				format.html { redirect_to '/user/'+current_user.pretty_name }
			else
				format.html { redirect_to '/' }
			end
		end
	end
	
	def api_score
		@error_message = ""
		@error_code = 1
		puts params
		if params.nil? or (params[:from].nil? or params[:to].nil?)
			@error_message = "Missing required arguments: " + ApplicationHelper.missing_arguments(params, ['from','to'])
		else
			@error_code = 4
			@user_from = User.find_by_username(params[:from].downcase)
			
			@user_to = User.find_by_username(params[:to].downcase)
			if @user_from.nil? and @user_to.nil?
				@error_message = "'from' and 'to' usernames are invalid or do not exist"
			elsif @user_from.nil?
				@error_message = "'from' username is invalid or does not exist"
			elsif @user_to.nil?
				@error_message = "'to' username is invalid or does not exist"
			else
				@error_code = 0
				if @user_from == @user_to
					@score = nil
				elsif !@user_from.master.nil? and (@user_from.master == @user_to or @user_from.master == @user_to.master)
					@score = nil
				elsif !@user_to.master.nil? and (@user_to.master == @user_from or @user_from.master == @user_to.master)
					@score = nil
				else
					@score = DepthFirstSearch.score(@user_from, @user_to)
				end
			end
		end
		
		
		if @error_code == 0
			@output = {:status=>"success", :score=>@score}
		else
			@output = {:status=>"error",
				:error_code=>@error_code,
				:error_message=>@error_message}
			end

			respond_to do |format|
				format.json { render json: @output}
			end
		end

		def new
			@user = User.new
			respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @user }
		end
	end
	
	
	
	def send_verification_email(address, user)
		@code = ApplicationHelper.random_token
		user.code = @code
		if user.save
			begin
				MyMailer.verificationmail(address, user.pretty_name, @code).deliver
			rescue Exception => e
				puts "EMAIL FAILED TO SEND"
				puts e.message
				return "Verification link could not be sent."
			end
			return "A verification link has been emailed to you."
		else
			return "Verification link could not be sent."
		end
	end


	def verification_email
		if current_user.nil?
			respond_to do |format|
				format.html { redirect_to '/' }
			end
		else
			respond_to do |format|
  				#attempt to send the email.
  				@notice = send_verification_email(current_user.email, current_user)
  				puts @notice
  				puts "EMAIL!"
  				format.html { redirect_to '/user/'+current_user.pretty_name, :notice => @notice }
  			end
  		end
  	end
  	
  	
  	def verify
  		@code = params[:code]
  		@notice = "We couldn't verify your email with this link. Try resending the verification email."
  		if current_user.code == @code
  			current_user.email_verified = true
  			current_user.code == nil
  			if current_user.save
  				@notice = "Email successfully verified!"
  			end
  		end
  		respond_to do |format|
  			format.html { redirect_to '/user/'+current_user.pretty_name, :notice => @notice }
  		end
  	end




  	def show_settings
  		@association_request = AssociationRequest.new
  		@user = current_user
  		respond_to do |format|
			format.html # show_settings.html.erb
		end
	end
	
	def confirm_ratings
		@user = current_user
		@envelopes = Rating.where("rater_id = ?", current_user.id).where("dateclosed IS NULL")

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def as_user

	end

	def something
	end
end

app/views/users/_associate.html.erb
<h2 class='subheader center'>forward to another Endorster account</h3>
<div class="large-8 large-offset-2 columns">


	<p class="justified">If you already have another Endorster account, you can <strong>forward all ratings</strong> from this account to that one. Then, all ratings sent or received by <a href="/user/<%= current_user.pretty_name %>"><%= current_user.pretty_name %></a>, in the past and in the future, will appear on the other account instead. This account's profile will redirect to the other one, and it will no longer be possible to log into this account.</p>

	<p class="justified"><strong>This action cannot be undone. Only do this if you are the owner of both accounts.</strong> You will need to log into the other account to confirm the connection.</p>

</div>
<div style="clear:both;"></div>

<div class="form large-6 large-offset-3 columns">
		<%= form_for(@association_request, :url=>"/profile/connect",  :html => {}, :id => "amy" ) do |f| %>
		<%= f.text_field :to, :placeholder => 'username of your other account' %>&nbsp;
		<%= f.submit "submit request",  class: "button right" %>

		<p><% if @association_request.errors[:to].length >0 %>
			<p class='messages'><%= @notice if @notice %></p>
			<p class="errorText"><%= @association_request.errors[:to].join(', ') %></p>
			<% end %>
			<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
 <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user_show_rating.html.erb
<h4 class='subheader'>
	<% if @user == current_user %>
	Ratings you've left for others.
	<%else%>
	Ratings <%= @user.pretty_name%> Has Left For Others
	<%end%>
</h4>
<% if @oratings.length > 0 %>
<% @oratings.each do |rating|%>
<tr>
	<td>
		<%= link_to rating.ratee.pretty_name, rating.ratee %>
	</td>
	<td><%= rating.signed_value.html_safe %></td>
	<% end %>
	<td/>
</tr>
</table>
<%else%>
<br>
Dust
<% end %>

<h4 class='subheader'>
	<% if @user == current_user %>
	Ratings Others Left For You
	<% else %>
	Ratings Others Left For <%= @user.pretty_name%>
	<% end %> 
	</h4>
	<% if @iratings.length > 0 %>
	<table>
		<% @iratings.each do |rating|%>
		<tr>
			<td><%= link_to rating.rater.pretty_name, rating.rater %></td>
			<td><%= rating.signed_value.html_safe %></td>
		</tr>
		<% end %>
	</table>
	<% end %>
</p>

app/views/users/activity.html.erb
<% if current_user == @viewing_user%>
	<h3 class='subheader'>your new notifications</h3>
	<% if current_user.notifications.length > 0  %>
		<ul class='no-style' style="background-color:#8f8;">
		<% current_user.notifications.each do |note| %>
		<li><a class='notification' href="<%=note.base_url+note.thing_id%>"> <%= note.text %></a> 
			</li> 
		<%end%>
		</ul>
		<%= link_to "dismiss all", dismiss_path, :class => 'button', :remote => :true %>
	<% else %>
		<p><i>no notifications</i></p>
	<% end %>
<% end %>

<h3 class='subheader'><%= @viewing_user.username %>'s activity </h3>
<ul class=no-style>
<% @ratings.each do |rate| %>
<% unless rate.rater == nil %>
<li>
<a href="/user/<%= rate.rater.pretty_name %>"><%= rate.rater.pretty_name %></a> gave 
<a href="/user/<%= rate.ratee.pretty_name %>"><%= rate.ratee.pretty_name %></a>
a rating of <%= rate.value %> <%= date_span(rate.created_at).html_safe %></li>

<%end%>
<%end%>
</ul>

app/views/users/associate.html.erb
<div class='panel center'>
	<h3 class='subheader'>forward to another Endorster account</h3>
</div>

<div>
	<p>You can connect this account with your other Endorster usernames. This will permanently merge all of the ratings on both accounts into one identity. <strong>You will need to confirm the connection from the other account.</strong>

		<div class="form">
			<%= form_for(@association_request, :url=>"/profile/connect") do |f| %>
			<label>Username:</label>
			<%= f.text_field :to , :style=>"width:72%" %>&nbsp;<%= f.submit "submit request", class: "largeButton" %>

			<p><% if @association_request.errors[:to].length >0 %>
				<p class="errorText"><%= @association_request.errors[:to].join(', ') %></p>
				<% end %>
				<% end %>
			</div>
		</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if @users && @users.length > 0 %>
	<p id="notice"><%= notice %></p>
	<table>
		<tr>
			<th>Username</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>

		<% @users.each do |user| %>
			<tr>
				<td><%= link_to user.username, user %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<p>No users found.</p>
<% end %>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="subheader center">sign up</h1>

<div class="large-6 large-offset-3 columns">


<%= form_for(@user, :url=>url_for(:controller => 'users', :action => 'create')+(params[:next].nil? ? '' : '?next='+params[:next])) do |f| %>
<%= f.text_field :username, :placeholder => 'username'  %>

<% if @user.errors[:username].length >0 %>
<span class="errorText">username <%= @user.errors[:username].join(', ') %></span>
<% end %>


<%= f.text_field :email, :placeholder => 'email (optional)'  %>

<% if @user.errors[:email].length >0 %>
<span class="errorText">email <%= @user.errors[:email].join(', ') %></span>
<% end %>

<%= f.password_field :password, :placeholder => 'password' %>

<% if @user.errors[:password].length >0 %>
<span class="errorText">password <%= @user.errors[:password].join(', ') %></span>
<% end %>

<%= f.password_field :password_confirmation, :placeholder => 'confirm password'  %>

<% if @user.errors[:password_confirmation].length > 0 %>
<span class="errorText">password confirmation <%= @user.errors[:password_confirmation].join(', ') %></span>
<% end %>

<%= f.submit "sign up", class: "button right" %>
<% end %>

</div>

app/views/users/notification.html.erb
<h3 class='subheader'>Notifications</h3>

app/views/users/show.html.erb
<div class='small-12 columns'>
	<% unless notice.nil? %>
	<div id="notice">
		<%= notice %>
	</div>
	<% end %>

	<div class="row">
	<h2 class="subheader left" style="margin-top:0"><%= @viewing_user.pretty_name %></h2>
	
	<% if current_user %>
		<% if current_user != @viewing_user %>
			<a class="button right" href="/invite?user=<%= @viewing_user.pretty_name %>">invite rating</a>
		<% else %>
			<a class="button right" href="/profile">edit profile</a>
		<% end %>
	<% end %>
	</div>


	<div class="row">

		<div style="border: 1px solid #aaa; width:200px;text-align:center; float:left; margin:0 10px 10px 0; -moz-border-radius: 5px;
border-radius: 5px;">

			<% if current_user %>
			<div style="background-color:#<%= color_for_score @score %>; width:100%; padding:10px; font-size:20pt; -moz-border-radius: 5px 5px 0 0;
border-radius: 5px 5px 0 0;">
				
					<%= @score.nil? ? "this is you!" : display_score(@score).html_safe %>
				
				
			</div>	
			<% end %>


			<div style="padding:6px;"><%= date_span(@viewing_user.created_at,"joined ").html_safe %></div>

		</div>

		<p><%= @viewing_user.description %></p>

	</div>

	<hr style="margin-top:-10px;"/>

	<h4 class="subheader" style="margin-top:-10px"><%= @viewing_user.pretty_name %>'s identities</h4>

	<% if @connections.length > 0 %>
		<p><% @connections.each_with_index do |connection,index| %>
			<a target="_blank" href="<%= connection.show_homepage_url %>"><%= connection.website_name %></a><% if index != @connections.length-1 %> &middot; <% end %>
		<% end %></p>
	<% else %>
		<p><i>none yet!</i></p>
	<% end %>


	<hr style="margin-top:-10px;"/>
	<h4 class="subheader" style="margin-top:-10px">ratings received</h4>

	<% if @iratings.length > 0 %>
		<table border=1>
			<% @iratings.each do |rating| %>
			<tr style="background-color:#<%= color_for_score(rating.value) %>">
				<td><a href="/user/<%= rating.rater.pretty_name %>"><%= rating.rater.pretty_name %>&nbsp;<sup><sup><%= display_score(DepthFirstSearch.score(current_user, rating.rater)).html_safe unless current_user.nil? %></sup></sup></a></td>
				<td><span style="font-size:16pt; font-weight:bold;"><%= display_score(rating.value).html_safe %></span></td>
				<td><%= rating.review %> <%= date_span(rating.dateclosed).html_safe %><% if current_user==rating.rater or current_user==rating.ratee %> (<%= rating.comment %>)<% end %></td>
			</tr>
			<% end %>
		</table>
	<% else %>
		<p><i>none yet!</i></p>
	<% end %>


	<hr style="margin-top:-10px;"/>
	<h4 class="subheader" style="margin-top:-10px">ratings given</h4>
	
	<% if @oratings.length > 0 %>
		<table border=1>
			<% @oratings.each do |rating| %>
			<tr style="background-color:#<%= color_for_score(rating.value) %>">
				<td><a href="/user/<%= rating.ratee.pretty_name %>"><%= rating.ratee.pretty_name %></a></td>
				<td><span style="font-size:16pt; font-weight:bold;"><%= display_score(rating.value).html_safe %></span></td>
				<td><%= rating.review %> <%= date_span(rating.dateclosed).html_safe %><% if current_user==rating.rater or current_user==rating.ratee %> (<%= rating.comment %>)<% end %></td></td>
			</tr>
			<% end %>
		</table>
	<% else %>
		<p><i>none yet!</i></p>
	<% end %>

</div>

app/views/users/signup.html.erb


<h2>Sign up</h2>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.text_field :password %>



      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/~edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>