config/routes.rb
RailsinstallerDemo::Application.routes.draw do
	#Reformed url scheme
	root :to => 'welcome#index'
	
	match 'user/:username/activity' => 'users#activity'

	match 'login' => 'user_sessions#new', :via => :get
	match 'login', :to => 'user_sessions#create', :via => :post
	match 'logout' => 'user_sessions#destroy', :as => :logout
	#resources :sessions, only: [:new, :create, :destroy]
	#resources :user_sessions
	
	match 'about' => 'welcome#about'
	match 'help' => 'welcome#help'
	match 'api/docs' => 'welcome#api_docs'
	match 'legal' => 'welcome#legal'

	match 'signup' => 'users#new', :via => :get
	match 'signup' => 'users#create', :via => :post
	
	match 'user/:id' => 'users#show', :as => :user
	
	match 'mark_read' => 'users#mark_read'
  match 'dismiss' => 'users#dismiss_notification', :as => :dismiss

	match 'dynamic_score' => 'users#dynamic_score'
	match ':username/notifications' => 'users#notifications'
	match 'public_events/:id' => 'users#public_events'
	match 'dynamic_search' => 'users#dynamic_search'

	match 'home' => 'users#home'
	
	match 'profile' => 'connections#index', :as => :connections, :via=>:get
	match 'profile' => 'connections#create', :as => :connections_create, :via=>:post
	match 'profile' => 'users#update_description', :as => :update_description, :via=>:put

	match 'profile/new' => 'connections#new', :as => :connections_new
	
	match 'profile/connect' => 'users#associate', :via => :get
	match 'profile/connect' => 'users#request_association', :via => :post
	match 'profile/connect/:id' => 'users#answer_association', :via => :get
	match 'profile/connect/:id/confirm' => 'users#confirm_association', :via => :get
	match 'profile/connect/:id/reject' => 'users#reject_association', :via => :get

	
	match 'activate/:code' => 'users#activate', :as => :activate, :via => :get
	match 'activate/:code' => 'users#finalize_activation', :as => :activate, :via => :put


	match 'invite' => 'rating_invitations#new', :via => :get
	match 'invite/new' => 'rating_invitations#create', :via => :post
	match 'invitation/:id' => 'rating_invitations#show'
	match 'invitation/:id/regenerate' => 'rating_invitations#regenerate', :as => :regenerate_invitation
	match 'invitation/:id/delete' => 'rating_invitations#delete', :as => :delete_invitation

	match '/i/:id' => 'rating_invitations#show_unique', :as => :i
	match '/accept/:id' => 'ratings#accept_invitation', :as => :accept
	match 'invite/email' => 'rating_invitations#email_invite', :via => :get
	match 'invite/email' => 'rating_invitations#send_email_invite', :via => :post

 
	
	match 'rate' => 'users#confirm_ratings'
	match 'rate/:id' => 'ratings#rate', :via => :get, :as => :rating
	match 'rate/:id' => 'ratings#update', :via => :put
	
	match 'share' => 'links#index', :via => :get
	match 'share' => 'links#create', :via => :post
	match 's/:id' => 'links#show'
	match 's/:id/delete' => 'links#destroy'
	
	match 'settings' => 'users#show_settings', :via => :get
	match 'settings' => 'users#update', :via => :put, :as => :update_settings
	match 'settings/v' => 'users#verification_email'
	match 'v/:code' => 'users#verify'
	
	match 'api/secure' => 'api#api_secure', :as => :api_secure, :via => :POST
	match 'api/score' => 'api#api_score', :as => :api_score, :via => :GET
	match 'api/signup' => 'api#api_signup', :as => :api_signup, :via => :POST
	match 'api/invitation' => 'api#api_invitation', :as => :api_invitation, :via => :GET
	match 'api/invite' => 'api#api_invite', :as => :api_invite, :via => :POST
	match 'api/rate' => 'api#api_rate', :as => :api_rate, :via => :POST
	match 'api/set_public_key' => 'api#api_set_public_key', :as => :api_set_public_key, :via => :POST
	match 'api/next_sequence' => 'api#api_next_sequence', :as => :api_next_sequence, :via => :GET
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :rater, :class_name => 'User'
  belongs_to :ratee, :class_name => 'User'
  belongs_to :referrer

  attr_accessible :rater, :ratee, :dateopened, :dateclosed, :unlimited, :lowerlimit, :upperlimit, :value, :comment, :unique_token
 

	
  validates_inclusion_of :unlimited, :in => [true, false]
  validates :value, :numericality => { :only_integer => true }
  validate :rating_valid, :on => :update
  validate :limits_valid

  	def is_in_range(proposed_value)
  		if unlimited
  			return true
  		else
  			if proposed_value < -lowerlimit or proposed_value > upperlimit
  				return false
  			else
  				return true
  			end
  		end
  	end

	def limits_valid
		if !unlimited
			unless lowerlimit.class == Fixnum
				errors.add(:lowerlimit, "has to be an integer")
			end

			unless upperlimit.class == Fixnum
				errors.add(:upperlimit, "has to be an integer")
			end

			unless lowerlimit.to_i > 0
				errors.add(:lowerlimit, "has to be greater than zero")
			end

			unless upperlimit.to_i > 0
				errors.add(:upperlimit, "has to be greater than zero")
			end
		end
	end

	def rating_valid
		if !value.nil? and !unlimited
			if value < -lowerlimit
				errors.add(:value, "is too low")
			elsif value > upperlimit
				errors.add(:value, "is too high")
			end
		end
	end


	def color
		return color_for_score(value)
	end
	
	def invitation_dict
		{:inviter => ratee.pretty_name,
		:invitee => rater.pretty_name,
		:upper_limit => unlimited ? 0 : upperlimit,
		:lower_limit => unlimited ? 0 : -1*lowerlimit,
		:date_opened => dateopened}
	end
	
	def set_master(master_user)
		master = master_user
		save
	end
	
	def signed_value
		if value == 0
			return '0'
		elsif value > 0
			return '+'+value.to_s
		elsif value < 0
			return '&minus;'+(-1*value).to_s
		end
	end
	
	#def can_only_rate_once
	#	errors.add(:value, "can only be rated once") if !dateclosed.nil?
	#end
end

app/controllers/ratings_controller.rb
require 'digest'
require 'application_helper'
include ApplicationHelper

class RatingsController < ApplicationController


	def new
		bubbles
	  @rating = Rating.new
		respond_to do |format|
			format.html  # new.html.erb
			format.json  { render :json => @rating }
		end
	end

	

	def create
		unlimited = params[:rating]["unlimited"]
		if unlimited != '0'
			upp = 1
			low = 1
		else
			upp = params[:rating]["upperlimit"]
			low = params[:rating]["lowerlimit"]
		end
		rater_user = User.find_by_username(params[:rating]["rater"].downcase)
		@rating = Rating.new(
			:ratee => current_user,
			:rater => rater_user,
			:unlimited => params[:rating]["unlimited"],
			:upperlimit => upp,
			:lowerlimit => low,
			:comment => params[:rating]["comment"],
			:dateopened => DateTime.now,
			:value => 0)
		user_found = true
	 	if rater_user.nil? and params[:rating]["rater"] != ''
			@rating.errors[:base] << "Can't find user"
			user_found = false
		end
		respond_to do |format|
			if @rating.save and user_found
			  format.html  { redirect_to(@rating.rater,
							:notice => 'Invitation was sent successfully.') }
			  format.json  { render :json => @rating,
							:status => :created, :location => @rating}
			else
			  format.html  { render :action => "new" }
			  format.json  { render :json => @rating.errors,
							:status => :unprocessable_entity }
			end
		end
	end

	

	#def show #This should never be called.
	#	redirect_to root_url
	#end
	


	def rate
		@rating = Rating.find(params[:id])
		
		if @rating.dateclosed or current_user.nil? or @rating.rater != current_user
			redirect_to root_url
		else
			bubbles
			respond_to do |format|
				format.html  # show.html.erb
				format.json  { render :json => @post }
			end
		end
	end



	def update
	  @rating = Rating.find(params[:id])
		if @rating.rater == current_user and @rating.dateclosed == nil
			@rating.review = params[:rating][:review]
			@rating.value = params[:rating][:value]
			@rating.dateclosed = DateTime.now
			saved = @rating.save
		else
			redirect_to root_url
		end
		if saved
			Notification.generate_notification(:got_rated, @rating).save
			redirect_to("/rate", :notice => 'Rating has been confirmed.')
		else
			render :action => "rate", :status => :unprocessable_entity 
		end
	end


	def api_invitation
		error_code = 0
		id = params[:invitation_id]
		if id.nil?
			error_code = 1
			error_message = "Missing required argument: invitation_id"
		else
			@rating = Rating.find_by_id(id)
			if @rating.nil? or !@rating.dateclosed.nil?
				error_code = 4
				error_message = "invitation_id is invalid, or refers to a nonexistent or closed invitation"
			end
		end
		respond_to do |format|
			if error_code == 0
				format.json  { render :json => {
					:status=>"success",
					:invitation=>@rating.invitation_dict
				} }
			else	
				format.json  { render :json => {
					:status=>"error",
					:error_code=>error_code,
					:error_message=>error_message
				} }
			end
		end
	end

	

	def accept_invitation
		@rating = Rating.find_by_unique_token(Digest::SHA512::hexdigest(params[:id]))
		@rating.rater = User.find_by_username(params[:rating][:rater].downcase)
		@rating.unique_token = nil
		@rating.dateopened = DateTime.now

		# Around this point, we want to notify the issuer of the invitation that their invitation has been accepted.
		if @rating.save
			@notification = Notification.generate_notification(:invitation_accepted, @rating)
			@notification.save
			redirect_to("/rate", :notice => 'You have attached the invitation to your account.')
		else
			render :action => "accept_invitation", :status => :unprocessable_entity 
		end
	end
	
	
	def api_rate
		required_arguments = ['referrer','api_key','invitation_id','privilege_token','value']
		missing_arguments = ApplicationHelper.missing_arguments(params, required_arguments)
		if missing_arguments
			error_code = 1
			error_message = "Missing required arguments: " + missing_arguments
		else
			referrer = params[:referrer]
			api_key = params[:api_key]
			invitation_id = params[:invitation_id].to_i
			privilege_token = params[:privilege_token]
			value = params[:value].to_i

			
			
			ref = Referrer.find_by_name(referrer)
			invitation = Rating.find_by_id(invitation_id)
			if !invitation.dateclosed.nil?
				invitation = nil
			end
			
			if ref.nil? or !ref.authenticate(api_key)
				error_code = 3
				error_message = "referrer + api_key combination is invalid"
			elsif invitation.nil?
				error_code = 4
				error_message = "invitation_id is invalid or do not exist"
			elsif invitation.rater.privilege_tokens[referrer] != Digest::SHA512::hexdigest(privilege_token)
				error_code = 6
				error_message = "referrer lacks sufficient privileges to perform the requested action"
			elsif !invitation.unlimited and (value<(-invitation.lowerlimit) or value>invitation.upperlimit)
				error_code = 5
				error_message = "value is out of range: must be between lower_limit and upper_limit inclusive"
			else
				#Proceed!
				invitation.value = value
				invitation.dateclosed = DateTime.now
				if invitation.save and Notification.generate_notification(:got_rated, invitation).save
					error_code = 0
				else
					error_code = 9
					error_message = "Internal server error"
				end
			end
		end
		

		if error_code == 0
			@output = {:status=>"success"}
		else
			@output = {:status=>"error", :error_code=>error_code, :error_message=>error_message}
		end
		
		respond_to do |format|
			format.json { render json: @output}
		end
	end

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<div class="row">
  
	<div class="span4 offset4">
		<h2>Authorize rating</h2>
		<h4>from user "<% if @rating.rater %><%= @rating.rater.pretty_name %><% else %><%= params[:rr] %>
			<% end %>"</h4><br/>
		<%= form_for(@rating) do |f| %>
			<% if @rating.errors.any? %>
				<b style="color:#aa0000">Problem:
					<ul>
						<% @rating.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
				</ul></b>
			<% end %>

			<% if @rating.rater %>
				<%= f.hidden_field :rater, :value => @rating.rater.username %>
			<% else %>
				<%= f.hidden_field :rater, :value => params[:rr] %>
			<% end %>
			


			Limits: &ndash;<%= f.text_field :lowerlimit, :style=> "width: 35px;"  %> <i>to</i> +<%= f.text_field :upperlimit, :style=> "width: 35px;" %>
			<br/>
			Unlimited range?&nbsp;<%= f.check_box :unlimited, :onchange => "toggle_limits();" %><br/>

			<%= f.label :comment %>
			<%= f.text_field :comment %>

			<p>
			<%= f.submit "Authorize rating", class: "btn btn-large btn-primary" %>
			</p>

		<% end %>
	</div>
</div>

<script type="text/javascript">
  function disable(element) {
	element.disabled = true;
	element.style.backgroundColor = "LightGray";
	element.style.color = "Gray";
  }
  
  function enable(element) {
	element.disabled = false;
	element.style.backgroundColor = "White";
	element.style.color = "Black";
  }

  function toggle_limits() {
	if (document.getElementById('rating_unlimited').checked) {
		disable(document.getElementById('rating_lowerlimit'));
		disable(document.getElementById('rating_upperlimit'));
	}
	else {
		enable(document.getElementById('rating_lowerlimit'));
		enable(document.getElementById('rating_upperlimit'));
	}
  }
</script>



app/views/ratings/_rate_form.html.erb
<% unless notice.nil? %>
<div id="notice" onclick="$(this).css('display','none')">
	<%= notice %>
</div>
<% end %>


	<h1 class='subheader center'>confirm rating</h3>


	
	<h3 class='subheader center'>for: <b><%= link_to @rating.ratee.pretty_name, @rating.ratee %></b></h3>

	<h3 class='subheader center'>invited you: <%= date_span(@rating.dateopened).html_safe %></h3>

	<h3 class='subheader center'>their comment: <% if @rating.comment != "" %><%= @rating.comment %><% else %><i>(no comment)</i><% end %></h3>

	<div class="large-6 large-offset-3 columns">

	<%= form_for(@rating) do |f| %>
		<%= f.text_area :review, :placeholder => 'your comment (optional; will be visible publicly)' %>

		<%= f.text_field :value, :value => '', :placeholder => 'an integer'+(@rating.unlimited ? '' : ' from -'+@rating.lowerlimit.to_s+' to +'+@rating.upperlimit.to_s) %>
		<%= f.submit class: "button right", value:"confirm rating" %>
		

		<% if @rating.errors[:value].length > 0 %>
			<span class="errorText">value <%= @rating.errors[:value].join(', ') %></span>
		<% end %>
		
		
		<% end %>

	</div>





	

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>
<% if @ratings && @ratings.length > 0 %>
	<p id="notice"><%= notice %></p>
	<table border = 1>
		<tr>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>

		<% @ratings.each do |rating| %>
			<tr>
				<td><%= rating.rater %></td>
				<td><%= rating.ratee %></td>
				<td><%= rating.lowerlimit %></td>
				<td><%= rating.upperlimit %></td>
				<td><%= rating.unlimited %></td>
				<td><%= rating.comment %></td>
				<td><%= rating.dateopened %></td>
				<td><%= rating.dateclosed %></td>
				<td><%= rating.unique_token %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<p>No ratings found.</p>
<% end %>

<br/>

<%= link_to 'New rating', new_rating_path %>

app/views/ratings/new.html.erb
<%= render 'form' %>
 

app/views/ratings/rate.html.erb
<%= render 'rate_form' %>